name: Test on Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      DB_URL: 'mongodb://localhost:27017/mydatabase'
      secretKey: 'your_secret_key'
      
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.stats()'" --health-interval 10s --health-timeout 5s --health-retries 5
  
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}


      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps to install dependencies and run tests here
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
