name: Test on Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      DB_URL: 'mongodb+srv://fadec82729:AaVr1J1xgamhS8Vm@cluster0.kejrxhn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      secretKey: 'your_secret_key'

    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}


      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps to install dependencies and run tests here
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
